- include/yaramod/builder/yara_expression_builder.h
- src/builder/yara_expression_builder.cpp
- src/python/yaramod_python.cpp
- tests/cpp/builder_tests.cpp
- tests/python/test_builder.py
Added `doubleVal` expression to builder (#22) . `doubleVal` also added to python bindings and to tests.
> Added doubleVal to YaraExpressionBuilder

- tests/python/test_builder.py
- tests/python/test_parser.py
By chance, I found out that there are duplicate unit tests (they have both the same name and content). I found it a bit confusing, so I removed them, as it was probably only some copy-paste error. Is some cases, I figured out what probably should have been tested by the duplicate test. For example, there were two identical tests for structure access, but no test for array or dictionary access. In those cases, I didn't remove the test and I only fixed it.
> Removing duplicate python tests

- .travis.yml
- setup_env.sh
With this change, we can upgrade Python to version 3.5 and also gcc to version 7 (because of upcoming C++17 requirement).
Could you Petr please review the changes if it's ok? Thanks.
> Upgrade ubuntu to xenial in TravisCI

- doc/Doxyfile
Currently the doxygen documentation is generated only from files in `src/` directory.
Files in `include/` have valid doxygen documentation but are not processed. Because of this classes like `RegexpUnit` are missing from generated documentation.
Retdec does something similar: https://github.com/avast/retdec/blob/master/doc/doxygen/doxygen.cfg.in#L828
> Doxygen: Generate documentation from header files.

- include/yaramod/types/literal.h
- include/yaramod/types/token.h
- src/parser/parser_driver.cpp
- src/types/literal.cpp
- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
This PR brings two fixes of our POG based parser:
- Use strToNum instead of std::stol, because stol would make us troubles on Windows, where long is signed and has usually only 32 bits.
- Comments are printed as were written.
> Parse pog fixes

- include/yaramod/types/expressions.h
- include/yaramod/types/token_stream.h
- src/builder/yara_expression_builder.cpp
- src/parser/parser_driver.cpp
- src/python/yaramod_python.cpp
- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
Bugfix of issue #48: We insert LF or CR or CRLF depending on what is used in the file, more precisely which of the three line endings `\n`, `\r` or `\r\n` has been used last time.
> Autoformat adds \r or \n depending on newlines used in the file.

- src/builder/yara_expression_builder.cpp
- tests/cpp/builder_tests.cpp
Single term calls to conjunction()/disjunction() resulted in wrong
condition being produced. The reason is that token stream of the
underlying expression was not copied when it was constructed.
> Fixed builder conjunction/disjunction with single term

- src/builder/yara_rule_builder.cpp
- tests/cpp/builder_tests.cpp
YaraRuleBuilder allows now to create string meta with empty string as value.
> YaraRuleBuilder allows empty string meta values (issue #58)

- src/types/token_stream.cpp
- tests/cpp/builder_tests.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_builder.py
In this PR, we propose to add new lines after and or or. Also add lines inside brackets containing these conjunctions. Both
```
(
mutex(/abc/) or mutex(/def/)
)
```
and
```
(mutex(/abc/) or mutex(/def/))
```
will become this:
```
(
mutex(/abc/) or
mutex(/def/)
)
```
However, both
```
(
mutex(/abc/) or /*comment*/
mutex(/def/)
)
```
and
```
(
mutex(/abc/) or //comment
mutex(/def/)
)
```
will stay the same.
> Add new line after and and or conjunctions.

- include/yaramod/builder/yara_file_builder.h
- include/yaramod/parser/parser_driver.h
- include/yaramod/types/modules/module.h
- include/yaramod/types/yara_file.h
- include/yaramod/yaramod.h
- src/builder/yara_file_builder.cpp
- src/python/yaramod_python.cpp
- src/types/modules/cuckoo_module.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_builder.py
- tests/python/test_parser.py
This PR enables yaramod to parse files containing deprecated symbols / modules. We rename the default `ImportFeatures::All` to `ImportFeatures::AllCurrent` and add new `ImportFeatures::Everything` also loading deprecated symbols / modules.
Users that need deprecated symbols can simply pass `ImportFeatures::Everything` to the `Yaramod` class constructor.
> Deprecated import feature (issue #62)

- include/yaramod/parser/parser_driver.h
- include/yaramod/parser/value.h
- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
We are now able to parse nested regexp classes like `/[[]*+]/`, `/[\[\]*+]/` or even `/[[\]*+]/`.
> Implement parsing of nested regexp classes (issue #67)

- include/yaramod/parser/parser_driver.h
- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
This PR fixes the parser behaviour on regexp classes. The classes are now, similarly to yara ended with first unescaped ].
> Regexp classes are now ended with first occurence of unescaped ]

- include/yaramod/builder/yara_file_builder.h
- src/builder/yara_file_builder.cpp
- tests/cpp/builder_tests.cpp
- tests/python/test_builder.py
Imports builded by YaraFileBuilder will be sorted in lexicographical order and without duplicities.
> Builder: avoid duplicity of imports, sort imports lexicographically

- src/parser/parser_driver.cpp
This PR fixes parser to preserve line endings used in the parsed files.
> Parser preserves CRLF line endings on Windows (part of YARA-632)

- include/yaramod/builder/yara_expression_builder.h
- include/yaramod/types/token_stream.h
- src/builder/yara_expression_builder.cpp
- src/types/token_stream.cpp
- tests/cpp/builder_tests.cpp
- tests/cpp/parser_tests.cpp
This PR implements autoformatting [improvement](https://github.com/avast/yaramod/wiki/Autoformatting#indenting-comments-inside-rule-sections) and also improves commented conjunctions / disjunctions produced in builder.
> Align comments

- include/yaramod/types/token_stream.h
- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
This feature removes double blank lines and use just one blank line instead when there is too many blank lines in the rule (Iff more than one third of the new-lines in the rule is followed by another new-line). The removing is only performed inside of rules.
> Remove blank lines

- include/yaramod/types/meta.h
- src/types/meta.cpp
- src/types/rule.cpp
- src/types/token.cpp
- tests/cpp/parser_tests.cpp
This PR fixes some less frequently used `Rule` methods that we recently found out misbehave. The problem is that these methods `Rule::addMeta`, `Rule::addTags` and `Rule::removeMetas` did not handle the TokenStream well and left the formatted text unchanged. In this PR we fix these methods, however there are still quite some methods left unfixed. These methods shall be fixed in the future in the issue #84.
> Fix addMeta, removeMetas and setTags handle of TokenStream

- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
This PR modifies the autoformatting of `and` and `or` conjunctions in a way, that it removes any new lines that precede this conjunctions. This change was requested in #79.
> Remove new line before and/or (#79)

- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
In case of a conjunction preceded by some newlines and a one-line comment:
```
true // cuckoo
and false
```
our autoformatter wrongly created
```
true // cuckoo and
false
```
This is fixed in this PR, where
```
//cuckoo
cuckoo.sync.mutex(/a/)
or cuckoo.sync.mutex(/b/)
//cuckoo
or cuckoo.sync.mutex(/c/)
or cuckoo.sync.mutex(/d/)
```
becomes this
```
//cuckoo
cuckoo.sync.mutex(/a/) or
cuckoo.sync.mutex(/b/) or
//cuckoo
cuckoo.sync.mutex(/c/) or
cuckoo.sync.mutex(/d/)
```
> Fix conjunction placement

- include/yaramod/types/modules/metadata_module.h
- include/yaramod/types/modules/modules.h
- include/yaramod/types/modules/modules_pool.h
- src/CMakeLists.txt
- src/types/modules/metadata_module.cpp
- tests/cpp/parser_tests.cpp
New module `metadata` only for Avast.
`metadata` module contains:
* `metadata.file.name("string")`
* `metadata.file.name(/regex/)`
* `metadata.detection.name(/regex/)`
* `metadata.detection.name("av_name", /regex/)`
Signed-off-by: Peter Tisovčík <peter.tisovcik@avast.com>
> New metadata module

- include/yaramod/builder/yara_rule_builder.h
- include/yaramod/types/rule.h
- src/builder/yara_rule_builder.cpp
- src/parser/parser_driver.cpp
- src/python/yaramod_python.cpp
- src/types/rule.cpp
- tests/cpp/parser_tests.cpp
I've went ahead and tried to fix the issue I've found. I hope my C++ is adequate.
I tried to be careful not to introduce any regressions and memory leaks, but please do check.
I've also added a test to `parser_tests.cpp` but had problems building the test suite, so I just hope the test works. I tested my fixes by hand, using the python bindings instead:
```python
import yaramod
test = """
/* comment test */
private global rule Kot
{
strings:
$a = "dummy1"
condition:
$a
}
/* comment test */
global private rule Hmm
{
strings:
$a = "dummy1"
condition:
$a
}
/* this will not work:
global global rule Zzz
{
strings:
$a = "dummy1"
condition:
$a
}
*/
private rule private_rule {
condition:
true
}
global rule global_rule {
condition:
true
}
""" …
```
> Fix parsing of "private global" rules

- src/types/modules/elf_module.cpp
Added `symtab_symbol` into attributes of `elf` module.
This change is related to [this]( https://github.com/VirusTotal/yara/pull/1256/).
> Added symtab_symbol function to elf module

- include/yaramod/types/expressions.h
- src/examples/cpp/dump_rules_ast/dumper.h
- src/examples/python/dump_rules_ast.py
- src/python/yaramod_python.cpp
fix for #103 , it does the job for me, not sure if there's a better way (one of the setters is technically not used, but it seemed like similar attributes had it as well).
> access to the "id" attribute in ForIntExpression (fix: #103)

- include/yaramod/types/expressions.h
- tests/cpp/builder_tests.cpp
This PR fixes and tests ForIntExpression::_id getter and setters which were introduced in #109. Together with #109 it solves #103.
> Fix and test ForIntExpression id getter and setters (#10)

- include/yaramod/types/rule.h
- src/types/rule.cpp
- tests/cpp/parser_tests.cpp
This PR adds a new `Rule` class setter `setModifiers` which allows to set the yara rule modifiers `private` and `global`. Solves #105.
> Add Rule::setModifiers() setter (#105)

- src/types/modules/cuckoo_module.cpp
- tests/cpp/parser_tests.cpp
Added parsing of functions `cuckoo.process.class_created()`, `cuckoo.process.class_searched()`, `cuckoo.process.window_created()` and `cuckoo.process.window_searched()`.
> Added support for classes and windows

- include/yaramod/types/rule.h
- src/python/yaramod_python.cpp
- src/types/rule.cpp
Code duplication avoided by using: https://stackoverflow.com/questions/856542/elegant-solution-to-duplicate-const-and-non-const-getters
However, it might have its downsides.
RetDec heavily uses `const getMetaWithName()` because it does not need to modify anything. I would have to refactor a lot of code just to remove all `const`, which does not seem right.
If you don't object, I would like to have this in Yaramod.
> yaramod/types/rule.h: add const getMetaWithName() version

- include/yaramod/parser/location.h
- include/yaramod/parser/parser_driver.h
- include/yaramod/types/hex_string.h
- include/yaramod/types/string.h
- src/builder/yara_hex_string_builder.cpp
- src/parser/parser_driver.cpp
- src/python/yaramod_python.cpp
- src/types/hex_string.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
Fixing the location of tokens of strings.
> Fix token location computing

- include/yaramod/builder/yara_hex_string_builder.h
- include/yaramod/types/expressions.h
- include/yaramod/types/rule.h
- include/yaramod/types/string.h
- include/yaramod/types/symbol.h
- include/yaramod/types/token.h
- include/yaramod/types/token_type.h
- include/yaramod/types/yara_file.h
- src/builder/yara_expression_builder.cpp
- src/builder/yara_file_builder.cpp
- src/builder/yara_hex_string_builder.cpp
- src/builder/yara_rule_builder.cpp
- src/parser/parser_driver.cpp
- src/types/rule.cpp
- src/types/token.cpp
- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
- tests/cpp/tokenstream_tests.cpp
Follow up to conversation about `TokenType` from #120.
> TokenType: convert to cpp11 enum class

- tests/python/test_visitor.py
I have added one more test of ModifyingVisitor. This one attempts to create a new rule `ANOTHER_RULE` and add it into an existing file. It also modifies each present rule to refer to the newly created `ANOTHER_RULE`.
> Add test of RuleInserter

- include/yaramod/utils/trie.h
Fixed the order of results from `Trie::getValueWithPrefix`.
> Fix Trie::getValueWithPrefix to return values in the correct order

- CMakeLists.txt
- cmake/FindFilesystem.cmake
- src/CMakeLists.txt
Older GCC needs to be linked against stdc++fs and Clang against c++fs.
> Fixed issues with older compilers not providing symbols for std::filesystem functions

- cmake/FindFilesystem.cmake
- include/yaramod/types/modules/module_pool.h
- include/yaramod/utils/filesystem.h
- include/yaramod/utils/filesystem_operations.h
- src/CMakeLists.txt
- src/parser/parser_driver.cpp
- src/types/modules/module_pool.cpp
- src/utils/filesystem_operations.cpp
We use either `std::experimental::filesystem` or `std::filesystem` depending on their availability.
> Include filesystem based on available filesystem library

- modules/module_pe.json
`pe.rich_signature.raw_data` and `pe.rich_signature.clear_data` are set incorrectly to integer type, which causes parser to fail on valid rules like this:
```
import "pe"
import "hash"
rule test {
condition:
hash.md5(pe.rich_signature.clear_data) == "d41d8cd98f00b204e9800998ecf8427e"
}
```
It fails with `No matching overload of function 'md5' for these types of parameters: Unexpected argument types for function md5 ( int )`
Issue was introduced in commit 0d07529.
> Fix pe.rich_signature types

- include/yaramod/parser/parser_driver.h
- include/yaramod/types/expressions.h
- include/yaramod/types/symbol.h
- include/yaramod/types/token_type.h
- src/parser/parser_driver.cpp
- src/python/yaramod_python.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
This PR solves issue [#45](https://github.com/avast/yaramod/issues/45) and allows parsing of:
-  incomplete rules (we can get TokenStream after parsing)
-  rules containing unknown identifiers (we can get text, text_formatted and condition)
-  YARA files importing non-existent files (we can get text, text_formatted and condition)
> Parsing of incomplete rules

- include/yaramod/builder/yara_file_builder.h
- include/yaramod/parser/parser_driver.h
- src/builder/yara_file_builder.cpp
- src/parser/parser_driver.cpp
- tests/python/test_builder.py
This PR fixes a problem of `YaraFileBuilder::get` method, which when given `recheck=True` did not use any custom provided modules in the `YaraFileBuilder::_module_pool` attribute of the particular `YaraFileBuilder` instance.
> Fix YaraFileBuilder recheck with custom modules

- src/parser/parser_driver.cpp
- src/types/token_stream.cpp
- tests/cpp/visitor_tests.cpp
It's still not ideal because for example for rule
```yara
condition:
1 of [
cuckoo.sync.mutex(/a/),
cuckoo.sync.mutex(/b/)
]
```
is formatted into
```yara
condition:
1 of [
cuckoo.sync.mutex(/a/),
cuckoo.sync.mutex(/b/)
]
}
```
but at least it no longer crashes. Once it's merged please release 3.9.2 as a hotfix release.
> Hotfix for user-defined arrays to be handled correctly by autoformatter

- modules/module_pe.json
This is a follow up of [PR #1509](https://github.com/VirusTotal/yara/pull/1509) in yara repository.
Added `pe.version_info_list` and `pe.number_of_version_infos` artefacts.
> Added `pe.version_info_list` and `pe.number_of_version_infos` artefacts

- include/yaramod/types/token.h
- tests/cpp/parser_tests.cpp
Hotfix provided in [#170](https://github.com/avast/yaramod/pull/170) did not cover proper indenting which this PR solves as can be seen in the added test.
> Make multiline custom arrays indent proper

- include/yaramod/parser/value.h
- include/yaramod/types/rule.h
- include/yaramod/types/sections_summary.h
- src/CMakeLists.txt
- src/parser/parser_driver.cpp
- src/types/rule.cpp
- src/types/sections_summary.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
Up until now, you could only define first strings and then variables. Defining variables and then strings was not supported by the parser, even though YARA supports such rule.
The only supported way of defining strings and variables:
```
rule r {
strings:
$1 = "one"
variables:
var = 123
condition:
true
}
```
Unsupported rule that throws an error:
```
rule r {
variables:
var = 123
strings:
$1 = "one"
condition:
true
}
```
From now on, the parser will successfully parse rules with string and variable sections defined in reverse order as well. The default section order when regenerating such rule back into fulltext representation is going to stay like it used to- first strings and then variables.
> Interchangeable strings and variables sections

- CHANGELOG.md
- docs/rtd/requirements.txt
- src/types/token_stream.cpp
- tests/python/test_parser.py
- tests/python/testing_rules/testing_file_with_import.yar
Solving #130 so that includes and imports are separated by newlines respectfully to any comments between.
Also Sphinx used in documentation build needed to be updated.
> Separate includes and imports

- CHANGELOG.md
- src/types/rule.cpp
- tests/cpp/yaramod_tests.cpp
> Fix meta placement after comment.

- CHANGELOG.md
- include/yaramod/types/literal.h
- include/yaramod/types/token.h
- include/yaramod/utils/utils.h
- src/types/literal.cpp
- src/utils/utils.cpp
- tests/cpp/parser_tests.cpp
Solving #149. Please note the following properties of the solution:
- Only one-line comments are stripped of trailing whitespaces, because when somebody prefers /* comment */ to /*comment*/ I do not intend to make them angry.
- The comments are stripped during their construction, thus only once. I could have made it the other way, so that the comments would be stripped every time we print TokenStream, but we do not need to store the information about where were the whitespaces. Sorry for mentioning this if it is obvious.
> Trim whitespaces of oneline comments

- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
I've tried to fix issue #186.
This was suspiciously easy (especially compared to my previous PR: #93), so please check that I don't do something obviously wrong. FWIW this fixes the issue at hand. Using the POC from the linked issue:
```python
import yaramod
y = yaramod.Yaramod(yaramod.Features.AllCurrent)
yara_file = y.parse_string(r'''
rule regex_test {
strings:
$a = /1\x32?3/
condition:
$a
}''')
for rule in yara_file.rules:
for string in rule.strings:
for unit in string.unit.units:
print(type(unit), unit.text)
```
Previous results:
```
<class 'yaramod.RegexpText'> 1
<class 'yaramod.RegexpText'> \x
<class 'yaramod.RegexpText'> 3
<class 'yaramod.RegexpOptional'> 2?
<class 'yaramod.RegexpText'> 3
```
Current (correct) results:
```
<class 'yaramod.RegexpText'> 1
<class …
```
> Fix escaped character handling in regex

- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
Another small PR from me. This time I've tackled #141.
After merging this, empty `strings:` section won't be allowed. I achieve this by adding a new rule for `strings_body_nonempty` that cannot be empty, and using it instead of `strings_body` in the main derivation. 
This is not related to any issue with mquery, but saw that issue on the issue list and figured I can try to solve it. I realise it's very low priority, but probably also won't hurt.
fixes: #141
> Make empty strings section invalid

- modules/module_pe.json
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
Include missing algorithm_oid attribute from YARA
> Add missing algorithm_oid from PE module

- modules/module_elf.json
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
This PR includes missing attributes from YARA ELF module - dynsym_entries and dynsym
> Add dynsym_entries and dynsym ELF module attributes

- modules/module_pe.json
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
Additionally to the ticket's instructions, we migrate:
pe.imports and pe.number_of_delayed_imports
We also solve YARA-1747 by adding pe.entry_point_raw
> YARA-1551: Yara42 pe module attributes

- modules/module_math.json
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
Mirrors the changes in yara introduced here:
https://github.com/VirusTotal/yara/commit/87bc03d58743aaaa0f11b6d19d1d26e717f3cb01
https://github.com/VirusTotal/yara/commit/0d5f2cd5ef2595d93886db05d970107f83c494d7
https://github.com/VirusTotal/yara/commit/2edd10c735d91120f0f567c893093c873a67ba95
Solves YARA-1550, YARA-1552 and YARA-1556.
> YARA-1550: Yara42 new math attributes

- include/yaramod/builder/yara_rule_builder.h
- include/yaramod/types/rule.h
- include/yaramod/types/token_stream.h
- include/yaramod/types/yara_file.h
- src/builder/yara_rule_builder.cpp
- src/parser/parser_driver.cpp
- src/types/rule.cpp
- src/types/token_stream.cpp
- src/types/yara_file.cpp
- tests/cpp/visitor_tests.cpp
- tests/python/test_parser.py
Removing all relevant tokens when deleting YARA rule from `YaraFile` instance.
> YARA-1806: Fix removing of parts of rules in tokenstream

- include/yaramod/builder/yara_expression_builder.h
- tests/cpp/builder_tests.cpp
When using builder interface, strings couldn't benefit from implicit cast to booleans, since they were excluded from all the types that can be casted to bools.
> Allow strings to have implicit conversion to bool same as YARA

- docs/rtd/parsing_rulesets.rst
- include/yaramod/parser/parser_driver.h
- include/yaramod/parser/uid_generator.h
- include/yaramod/types/expression.h
- src/parser/parser_driver.cpp
- src/python/yaramod_python.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_parser.py
I've added UIDGenerator as part of the ParserDriver, which assigns UIDs to AST nodes that have `class Expression` as their base class.
The UIDs are supposed to be unique for a given input and deterministic, they are implemented using a 64bit resettable counter. The counter is reset when new parsing input is provided using the existing `prepareParser()` function and when the condition rule is applied, so it's reset before parsing each condition.
I've modified the existing rule condition AST dumper example code, to print the UIDs and for input:
```
rule ExampleRule
{
strings:
$my_text_string = "text here"
$my_hex_string = { E2 34 A1 C8 23 FB }
$a = "text1"
condition:
$my_text_string or $my_hex_string and
not $a or false
}
rule ExampleRule1
{
strings:
$my_text_string = "text here" private …
```
> Generate UIDs for AST nodes with Expression base class

- CMakeLists.txt
Some system hasn't got python2 anymore, and ships only with python3. This mean that `python` command is unavailable.
This trivial patch started to use `find_package` to detect the real python binary which should be used.
> Use the right python to create `WRAP_MODULE_SOURCES`

- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
This fixes parsing of regexes like `/(a|b|)/` which are valid YARA but we weren't able to handle empty alternation groups. Fixes #193.
> fix(parser): Fixed parsing of empty alternation groups (#193)

- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
- tests/python/test_builder.py
- tests/python/test_parser.py
Added support for string literal sets, that are supported in YARA 4.3. Also added corresponding parser and builder tests.
> String literal sets

- src/types/rule.cpp
- tests/python/test_representation.py
Currently, after we delete tags from the rule, we would still have a `:` with empty tag list. Which is a incorrect syntax. For example:
```yara
rule foo : bar {
condition:
true
}
```
will become (which should not happen)
```yara
rule foo : {
condition:
true
}
```
This patch refactors the `Rule::setTags` method to always delete the old tags if present. And then add new tags only if necessary.
> fix(Rule): Delete tags from the rule

- include/yaramod/parser/parser_driver.h
- include/yaramod/types/yara_file.h
- src/parser/parser_driver.cpp
- src/python/CMakeLists.txt
- src/python/yaramod_python.cpp
- src/types/yara_file.cpp
- tests/cpp/parser_tests.cpp
This change adds new deferred include parsing mode which is an extension of incomplete parsing mode. On top of allowing rules to use undefined symbols, it additionally does not resolve include directives and let's user to handle them.
Incomplete mode was also broken for a long time by not allowing to parse incomplete rules when they used a module for which the definition was missing. This change forces the import of said module.
> Added deferred include parsing mode + fixed incomplete mode when import of a module is missing

- include/yaramod/parser/parser_driver.h
- src/parser/parser_driver.cpp
- tests/cpp/parser_tests.cpp
We were incorrectly marking certain expression arrays like `(true, $str)` as string arrays while they should have been mixed expression arrays.
> fix: Expression array type is now properly recognized

- src/builder/yara_expression_builder.cpp
- tests/cpp/builder_tests.cpp
- tests/cpp/visitor_tests.cpp
The iterables should now be preferred to have parantheses and not square brackets.
> feat: Builder now creates new types of iterables with iterable()

- src/parser/parser_driver.cpp
- src/types/token_stream.cpp
- tests/cpp/parser_tests.cpp
Formatting of token stream worked incorrectly with new expression arrays (using regular parentheses instead of square brackets) and it was producing broken YARA files.
This not only fixes that, but also fixes:
* Formatting for nested expression arrays which didn't work properly even before
* Forcing correct spacing around function calls and arrays accesses (with no spaces around these brackets)
And I also added test for testing all of this since it seems like it wasn't really covered.
> Several formatting fixes
